'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ProjetProcessusUnifier.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _240_F_45061001_ze8PWtzQUS3uXLqQv5JL6CWy8jR4bslQ() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("240_F_45061001_ze8PWtzQUS3uXLqQv5JL6CWy8jR4bslQ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _31833983_bouton_annuler_carré_tridimensionnel_rouge_isolé_sur_fond_blanc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("31833983-bouton-annuler-carré-tridimensionnel-rouge-isolé-sur-fond-blanc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _37293750_vector_illustration_de_la_croix_rouge_rouge_icône_quot_x_quot_le_bouton_fermer_incorrecte_cesser_de_fum() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("37293750-vector-illustration-de-la-croix-rouge-rouge-icône-quot-x-quot-le-bouton-"& _ 
                        "fermer-incorrecte-cesser-de-fum", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _37293750_vector_illustration_de_la_croix_rouge_rouge_icône_quot_x_quot_le_bouton_fermer_incorrecte_cesser_de_fum1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("37293750-vector-illustration-de-la-croix-rouge-rouge-icône-quot-x-quot-le-bouton-"& _ 
                        "fermer-incorrecte-cesser-de-fum1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _500_F_32388607_gcswRr1b2RQB7tLs2EgiXAsPEqC1kfdH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("500_F_32388607_gcswRr1b2RQB7tLs2EgiXAsPEqC1kfdH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _64093868_résumé_vignette_de_dégradé_de_couleur_résumé_couleur_sombre_fond_bleu_dégradé_design_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("64093868-résumé-vignette-de-dégradé-de-couleur-résumé-couleur-sombre-fond-bleu-dé"& _ 
                        "gradé-design-", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _8714750_image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("8714750.image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property avertissement_signe_exclamation_pression_mark_jaune_icone_feux_erreur_point_lattention_vector_triangle_symbole_isole_gwgdkp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("avertissement-signe-exclamation-pression-mark-jaune-icone-feux-erreur-point-latte"& _ 
                        "ntion-vector-triangle-symbole-isole-gwgdkp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bouton_carré_orange_d_icône_arrière_de_flèche_104711540() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bouton-carré-orange-d-icône-arrière-de-flèche-104711540", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bouton_connexion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bouton connexion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property degrade_gris_bleu_1095_593() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("degrade-gris-bleu_1095-593", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property depositphotos_123432976_stock_photo_yellow_and_orange_gradient_abstract() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("depositphotos_123432976-stock-photo-yellow-and-orange-gradient-abstract", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property depositphotos_127154792_stock_photo_next_arrow_icon_shiny_red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("depositphotos_127154792-stock-photo-next-arrow-icon-shiny-red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property depositphotos_132779518_stock_video_night_sky_sparkly_stars_on() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("depositphotos_132779518-stock-video-night-sky-sparkly-stars-on", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property enregistrer_bouton() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("enregistrer-bouton", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property images() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property images1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property medecin_orl_copy_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medecin-orl-copy-1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property orl_article() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("orl_article", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pngtree_dark_gray_gradient_geometric_shape_banner_background_grey_gradient_backgroundgeometric_image_83305() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pngtree-dark-gray-gradient-geometric-shape-banner-background-grey-gradient-backgr"& _ 
                        "oundgeometric-image_83305", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
